version: 0.0
os: linux
files:
  - source: /admin-server-0.0.1.jar
    destination: /opt/app
hooks:
#  BeforeInstall:
#    - location: scripts/install_dependencies.sh
#      timeout: 300
#      runas: root
  AfterInstall:
    - location: scripts/executable.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
